# Generated by Django 5.0.7 on 2024-09-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='mana_point',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
