# Generated by Django 5.0.7 on 2024-08-09 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_player_card'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='player_rank',
            name='rarity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.rarity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player_rank',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='card',
            field=models.ManyToManyField(blank=True, related_name='player_cards', to='main.card'),
        ),
    ]
