# Generated by Django 5.0.7 on 2024-08-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_match_matchresult_playercard'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('ongoing', 'Ongoing'), ('finished', 'Finished')], default='waiting', max_length=20),
        ),
    ]
