# Generated by Django 5.0.7 on 2024-08-29 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_matchrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='hp',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='mana',
            field=models.IntegerField(default=100),
        ),
    ]
