# Generated by Django 5.0.7 on 2024-09-03 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_player_hp_alter_player_mana'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='can_nullify',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
